const REPO='akcollection/akcollection.github.io';let token='',site={},siteSha='',categories=[],catSha='',products=[];
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
function msg(t){const e=$('status');e.textContent=t;e.classList.add('show');clearTimeout(window._st);window._st=setTimeout(()=>e.classList.remove('show'),2600)}
function decode(b){return decodeURIComponent(escape(atob((b||'').replace(/\n/g,''))))}function encode(s){return btoa(unescape(encodeURIComponent(s)))}
async function api(path,opt={}){const r=await fetch('https://api.github.com/repos/'+REPO+'/contents/'+path,{...opt,headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+token,'Content-Type':'application/json'}});const j=await r.json();if(!r.ok)throw Error(j.message||'GitHub error');return j}
async function read(path){const j=await api(path);return {sha:j.sha,text:decode(j.content)}}
async function save(path,text,sha,message){const body={message,content:encode(text)};if(sha)body.sha=sha;return api(path,{method:'PUT',body:JSON.stringify(body)})}
function imagePath(p){return p?(p.startsWith('http')?p:'./'+p):''}
async function connect(){token=$('token').value.trim();if(!token)return msg('Paste your GitHub token.');try{msg('Loading store...');let s=await read('data/site.json'),c=await read('data/categories.json');site=JSON.parse(s.text);siteSha=s.sha;categories=JSON.parse(c.text);catSha=c.sha;let ls=await api('data/products');products=[];for(const f of ls.filter(x=>/\.json$/i.test(x.name))){let p=await read('data/products/'+f.name);products.push({...JSON.parse(p.text),_file:f.name,_sha:p.sha});}fillSite();renderCats();renderProducts();$('login').hidden=true;$('app').hidden=false;msg('Connected.');}catch(e){token='';msg('Connection failed: '+e.message)}}
$('connect').onclick=connect;$('logout').onclick=()=>{token='';location.reload()};
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')});
function fillSite(){const keys=['announcement','shipping','hero_label','hero_title','hero_emphasis','hero_text','hero_button','about_label','about_title','about_emphasis','about_text','contact_label','contact_title','contact_text'];$('siteForm').innerHTML=keys.map(k=>`<label>${k.replaceAll('_',' ').toUpperCase()}<input name="${k}" value="${esc(site[k]||'')}"></label>`).join('')}
$('saveSite').onclick=async()=>{try{document.querySelectorAll('#siteForm [name]').forEach(e=>site[e.name]=e.value);let j=await save('data/site.json',JSON.stringify(site,null,2)+'\n',siteSha,'Update website text from visual editor');siteSha=j.content?.sha||siteSha;msg('Website text saved.')}catch(e){msg(e.message)}};
function renderCats(){const box=$('categoryList');box.innerHTML=categories.map((c,i)=>`<div class="category" style="align-items:center;flex-wrap:wrap"><img src="${imagePath(c.image)}" style="width:72px;height:72px;object-fit:cover;border-radius:8px;background:#eee" onerror="this.style.display='none'"><div style="flex:1;min-width:220px"><label>Category ${i+1}<input data-cat-name="${i}" value="${esc(c.label||c.name||'')}"></label><small>${esc(c.image||'No image yet')}</small></div><input type="file" accept="image/*" data-cat-file="${i}" style="max-width:190px"><button class="danger" onclick="removeCat(${i})">Remove</button></div>`).join('')+`<button class="ghost" onclick="addCat()">+ Add Category</button>`}
window.addCat=()=>{categories.push({id:'category-'+Date.now(),name:'NEW CATEGORY',label:'NEW CATEGORY',image:'',link:'#collection'});renderCats()};window.removeCat=i=>{if(confirm('Remove this category?')){categories.splice(i,1);renderCats()}};
async function file64(file){return new Promise((res,rej)=>{let r=new FileReader();r.onload=()=>res(r.result.split(',')[1]);r.onerror=rej;r.readAsDataURL(file)})}
async function putBinary(path,file,sha){const content=await file64(file);const body={message:'Upload image from visual editor',content};if(sha)body.sha=sha;return api(path,{method:'PUT',body:JSON.stringify(body)})}
$('saveCategories').onclick=async()=>{try{for(const el of document.querySelectorAll('[data-cat-name]'))categories[+el.dataset.catName].name=categories[+el.dataset.catName].label=el.value;for(const el of document.querySelectorAll('[data-cat-file]')){const i=+el.dataset.catFile,f=el.files[0];if(!f)continue;const ext=(f.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z]/g,'')||'jpg';const path='media/categories/'+categories[i].id+'.'+ext;let oldSha=null;if(categories[i].image){try{oldSha=(await api(categories[i].image)).sha}catch(_){} }await putBinary(path,f,oldSha);categories[i].image=path;}let j=await save('data/categories.json',JSON.stringify(categories,null,2)+'\n',catSha,'Update categories from visual editor');catSha=j.content?.sha||catSha;renderCats();msg('Categories saved.')}catch(e){msg('Category save failed: '+e.message)}};
function renderProducts(){const box=$('productsList');box.innerHTML=products.map((p,i)=>`<div class="product"><img src="${imagePath(p.image)}" onerror="this.style.visibility='hidden'"><div><h3>${esc(p.name||'Untitled')}</h3><p>PKR ${Number(p.price||0).toLocaleString()} • ${esc(p.category||'Watches')}</p><p>${esc(p.description||'')}</p></div><div class="actions"><button class="primary" onclick="editProduct(${i})">Edit</button><button class="danger" onclick="deleteProduct(${i})">Remove</button></div></div>`).join('')||'<p>No products yet.</p>'}
function openModal(html){document.querySelector('.modal')?.remove();const d=document.createElement('div');d.className='modal';d.innerHTML='<div class="modalbox">'+html+'</div>';document.body.appendChild(d);return d}
window.editProduct=i=>{const p=products[i];const m=openModal(`<h2>Edit Product</h2><label>Name<input id="pn" value="${esc(p.name)}"></label><label>Category<input id="pc" value="${esc(p.category||'Watches')}"></label><label>Price<input id="pp" type="number" value="${p.price||0}"></label><label>Description<textarea id="pd">${esc(p.description||'')}</textarea><label>Product photo<input id="pi" type="file" accept="image/*"></label><div class="modal-actions"><button class="ghost" onclick="this.closest('.modal').remove()">Cancel</button><button class="primary" id="saveProd">Save</button></div>`);m.querySelector('#saveProd').onclick=async()=>{try{p.name=m.querySelector('#pn').value;p.category=m.querySelector('#pc').value;p.price=Number(m.querySelector('#pp').value)||0;p.description=m.querySelector('#pd').value;const f=m.querySelector('#pi').files[0];if(f){const ext=(f.name.split('.').pop()||'jpg').toLowerCase().replace(/[^a-z]/g,'')||'jpg';const path='media/products/'+p._file.replace(/\.json$/,'')+'.'+ext;let oldSha=null;if(p.image){try{oldSha=(await api(p.image)).sha}catch(_){} }await putBinary(path,f,oldSha);p.image=path;}let j=await save('data/products/'+p._file,JSON.stringify({name:p.name,category:p.category,price:p.price,description:p.description,image:p.image||'',active:p.active!==false},null,2)+'\n',p._sha,'Update product from visual editor');p._sha=j.content?.sha||p._sha;m.remove();renderProducts();msg('Product saved.')}catch(e){msg('Product save failed: '+e.message)}}};
$('newProduct').onclick=async()=>{const file='product-'+Date.now()+'.json';const p={name:'New Product',category:'Watches',price:0,description:'',image:'',active:true,_file:file,_sha:null};try{let j=await save('data/products/'+file,JSON.stringify({name:p.name,category:p.category,price:p.price,description:p.description,image:'',active:true},null,2)+'\n',null,'Add product from visual editor');p._sha=j.content?.sha||null;products.unshift(p);renderProducts();editProduct(0)}catch(e){msg('Could not add product: '+e.message)}};
window.deleteProduct=async i=>{if(!confirm('Remove this product?'))return;try{const p=products[i];if(p._sha)await api('data/products/'+p._file,{method:'DELETE',body:JSON.stringify({message:'Remove product from visual editor',sha:p._sha})});products.splice(i,1);renderProducts();msg('Product removed.')}catch(e){msg('Remove failed: '+e.message)}};
