const REPO='akcollection/akcollection.github.io';
let token='',site={},siteSha='',categories=[],catSha=[],products=[],theme={},themeSha='';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
function msg(t){const e=$('status');e.textContent=t;e.classList.add('show');clearTimeout(window._st);window._st=setTimeout(()=>e.classList.remove('show'),4000)}
function decode(b){return decodeURIComponent(escape(atob((b||'').replace(/\n/g,''))))}
function encode(s){return btoa(unescape(encodeURIComponent(s)))}
async function api(path,opt={}){const r=await fetch('https://api.github.com/repos/'+REPO+'/contents/'+path,{...opt,headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+token,'Content-Type':'application/json'}});const j=await r.json();if(!r.ok)throw Error(j.message||'GitHub error');return j}
async function read(path){const j=await api(path);return {sha:j.sha,text:decode(j.content)}}
async function save(path,text,sha,message){const body={message,content:encode(text)};if(sha)body.sha=sha;return api(path,{method:'PUT',body:JSON.stringify(body)})}
function imagePath(p){return p?(p.startsWith('http')?p:'./'+p):''}
async function connect(){token=$('token').value.trim();if(!token)return msg('Paste your GitHub token.');try{msg('Loading your complete store editor...');const s=await read('data/site.json'),c=await read('data/categories.json'),t=await read('data/theme.json');site=JSON.parse(s.text);siteSha=s.sha;categories=JSON.parse(c.text);catSha=c.sha;theme=JSON.parse(t.text);themeSha=t.sha;const ls=await api('data/products');products=[];for(const f of ls.filter(x=>/\.json$/i.test(x.name))){const p=await read('data/products/'+f.name);products.push({...JSON.parse(p.text),_file:f.name,_sha:p.sha})}fillSite();renderCats();renderProducts();renderMedia();fillTheme();$('login').hidden=true;$('app').hidden=false;msg('Connected — all visual controls are ready.')}catch(e){token='';msg('Connection failed: '+e.message)}}
$('connect').onclick=connect;$('logout').onclick=()=>{token='';location.reload()};
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>showTab(b.dataset.go));
function showTab(name){document.querySelectorAll('.tabs button').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id===name));const p=$(name);if(p)p.scrollIntoView({behavior:'smooth',block:'start'})}

const siteFields=[
['announcement','Top announcement','text'],['shipping','Shipping / service bar','text'],
['hero_label','Hero small label','text'],['hero_title','Hero main title','text'],['hero_emphasis','Hero highlighted word','text'],['hero_text','Hero description','textarea'],['hero_button','Hero button text','text'],
['trust1_title','Trust 1 title','text'],['trust1_text','Trust 1 subtitle','text'],['trust2_title','Trust 2 title','text'],['trust2_text','Trust 2 subtitle','text'],['trust3_title','Trust 3 title','text'],['trust3_text','Trust 3 subtitle','text'],['trust4_title','Trust 4 title','text'],['trust4_text','Trust 4 subtitle','text'],
['category_label','Category section label','text'],['category_title','Category section title','text'],['category_emphasis','Category highlighted word','text'],['category_button','Category card button text','text'],
['collection_label','Collection small label','text'],['collection_title','Collection title','text'],['filter_all','All filter label','text'],['filter_luxury','Luxury filter label','text'],['filter_classic','Classic filter label','text'],['filter_modern','Modern filter label','text'],['filter_search_placeholder','Search placeholder','text'],
['about_label','About small label','text'],['about_title','About title','text'],['about_emphasis','About highlighted words','text'],['about_text','About paragraph','textarea'],
['contact_label','Contact small label','text'],['contact_title','Contact title','text'],['contact_text','Contact paragraph','textarea'],['contact_button','Contact button text','text'],
['footer_brand','Footer brand name','text'],['footer_subtitle','Footer subtitle','text'],['footer_copyright','Footer copyright','text'],['browser_title','Browser page title','text'],['browser_description','SEO description','textarea']
];
function fillSite(){const f=$('siteForm');f.innerHTML=siteFields.map(([k,l,t])=>'<label>'+l+(t==='textarea'?'<textarea name="'+k+'">'+esc(site[k]||'')+'</textarea>':'<input name="'+k+'" value="'+esc(site[k]??'')+'">')+'</label>').join('')+'<div class="full"><h3>Show / hide sections</h3><div class="checks"><label><input type="checkbox" name="show_trust" '+(site.show_trust!==false?'checked':'')+'> Trust bar</label><label><input type="checkbox" name="show_categories" '+(site.show_categories!==false?'checked':'')+'> Categories</label><label><input type="checkbox" name="show_collection" '+(site.show_collection!==false?'checked':'')+'> Products</label><label><input type="checkbox" name="show_about" '+(site.show_about!==false?'checked':'')+'> About</label><label><input type="checkbox" name="show_contact" '+(site.show_contact!==false?'checked':'')+'> Contact</label></div></div>'}
$('saveSite').onclick=async()=>{try{document.querySelectorAll('#siteForm [name]').forEach(e=>site[e.name]=e.type==='checkbox'?e.checked:e.value);const j=await save('data/site.json',JSON.stringify(site,null,2)+'\n',siteSha,'Update complete visual website content');siteSha=j.content?.sha||siteSha;msg('All website text/settings saved.')}catch(e){msg('Save failed: '+e.message)}};

function renderMedia(){const items=[
['hero_background','Hero / Banner background','16:9 background image'],['hero_accessories','Hero main product image','Transparent/cutout image shown over banner'],['logo','AK Collection logo','Header, mobile and footer logo'],['hero_watch1','Hero watch 1','Optional floating watch image'],['hero_watch2','Hero watch 2','Optional floating watch image'],['hero_watch3','Hero watch 3','Optional floating watch image'],['hero_watch4','Hero watch 4','Optional floating watch image']
];$('mediaList').innerHTML=items.map(x=>{const p=theme[x[0]]||'';return '<div class="media-card"><div class="media-preview">'+(p?'<img src="'+imagePath(p)+'" onerror="this.style.opacity=.25">':'<span>No image set</span>')+'</div><div class="inside"><h3>'+x[1]+'</h3><p>'+x[2]+'</p><p><b>Current:</b> '+esc(p||'None')+'</p><div class="buttons"><label class="ghost" style="cursor:pointer">Upload & crop<input type="file" accept="image/*" data-media="'+x[0]+'" hidden></label><button class="ghost" onclick="clearMedia(\''+x[0]+'\')">Clear</button></div></div></div>'}).join('');
document.querySelectorAll('[data-media]').forEach(i=>i.onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const key=e.target.dataset.media;const aspect=key==='hero_background'?16/9:key==='logo'?1:4/5;const data=await cropImage(f,aspect);const ext=key==='logo'?'png':'jpg';const path='media/site/'+key+'-'+Date.now()+'.'+ext;await putDataUrl(path,data,null,'Upload '+key+' from visual editor');theme[key]=path;await saveThemeObject();renderMedia();msg('Image uploaded, cropped and saved.')}catch(err){msg('Image upload failed: '+err.message)}})}
window.clearMedia=async key=>{theme[key]='';try{await saveThemeObject();renderMedia();msg('Image removed and saved.')}catch(e){msg(e.message)}};
async function saveThemeObject(){const j=await save('data/theme.json',JSON.stringify(theme,null,2)+'\n',themeSha,'Update complete visual theme');themeSha=j.content?.sha||themeSha}
async function putDataUrl(path,dataUrl,sha,message){const body={message,content:dataUrl.split(',')[1]};if(sha)body.sha=sha;return api(path,{method:'PUT',body:JSON.stringify(body)})}

function renderCats(){const box=$('categoryList');box.innerHTML=categories.map((c,i)=>'<div class="category"><img src="'+imagePath(c.image)+'" onerror="this.style.visibility=\'hidden\'"><div class="fields"><label>Name<input data-cat-name="'+i+'" value="'+esc(c.label||c.name||'')+'"></label><label>Link<input data-cat-link="'+i+'" value="'+esc(c.link||'#collection')+'"></label><label>Button<input data-cat-button="'+i+'" value="'+esc(c.button||site.category_button||'SHOP NOW →')+'"></label><small>'+esc(c.image||'No image yet')+'</small></div><div class="category-actions"><label class="ghost" style="cursor:pointer">Photo<input type="file" accept="image/*" data-cat-file="'+i+'" hidden></label><button class="danger" onclick="removeCat('+i+')">Remove</button></div></div>').join('')||'<p>No categories. Add one.</p>';
document.querySelectorAll('[data-cat-file]').forEach(el=>el.onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const i=+el.dataset.catFile,data=await cropImage(f,4/3),path='media/categories/'+categories[i].id+'-'+Date.now()+'.jpg';await putDataUrl(path,data,null,'Update category image');categories[i].image=path;renderCats();msg('Category photo uploaded — click Save Categories.')}catch(err){msg(err.message)}})}
$('addCategory').onclick=()=>{categories.push({id:'category-'+Date.now(),name:'NEW CATEGORY',label:'NEW CATEGORY',image:'',link:'#collection',button:'SHOP NOW →'});renderCats()};
window.removeCat=i=>{if(confirm('Remove this category?')){categories.splice(i,1);renderCats()}};
$('saveCategories').onclick=async()=>{try{document.querySelectorAll('[data-cat-name]').forEach(e=>{categories[+e.dataset.catName].name=e.value;categories[+e.dataset.catName].label=e.value});document.querySelectorAll('[data-cat-link]').forEach(e=>categories[+e.dataset.catLink].link=e.value||'#collection');document.querySelectorAll('[data-cat-button]').forEach(e=>categories[+e.dataset.catButton].button=e.value||'SHOP NOW →');const j=await save('data/categories.json',JSON.stringify(categories,null,2)+'\n',catSha,'Update categories from visual editor');catSha=j.content?.sha||catSha;msg('Categories saved.')}catch(e){msg('Category save failed: '+e.message)}};

function renderProducts(){const box=$('productsList');box.innerHTML=products.map((p,i)=>'<div class="product"><img src="'+imagePath(p.image)+'" onerror="this.style.visibility=\'hidden\'"><div><h3>'+esc(p.name||'Untitled')+'</h3><p>PKR '+Number(p.price||0).toLocaleString()+' · '+esc(p.category||'Watches')+'</p><p>'+esc(p.description||'')+'</p><p>'+ (p.active===false?'HIDDEN':'VISIBLE')+'</p></div><div class="actions"><button class="primary" onclick="editProduct('+i+')">Edit</button><button class="danger" onclick="deleteProduct('+i+')">Remove</button></div></div>').join('')||'<p>No products yet.</p>'}
function openModal(html){document.querySelector('.modal')?.remove();const d=document.createElement('div');d.className='modal';d.innerHTML='<div class="modalbox">'+html+'</div>';document.body.appendChild(d);return d}
window.editProduct=i=>{const p=products[i],options=categories.map(c=>'<option '+(p.category===c.name||p.category===c.label?'selected':'')+'>'+esc(c.name||c.label)+'</option>').join('');const m=openModal('<h2>Edit Product</h2><div class="formgrid"><label>Name<input id="pn" value="'+esc(p.name)+'"></label><label>Category<select id="pc">'+(options||'<option>Watches</option>')+'</select></label><label>Price<input id="pp" type="number" value="'+(p.price||0)+'"></label><label>Description<textarea id="pd">'+esc(p.description||'')+'</textarea></label><label>Visibility<select id="pa"><option value="true" '+(p.active!==false?'selected':'')+'>Visible</option><option value="false" '+(p.active===false?'selected':'')+'>Hidden</option></select></label><label>Product photo<input id="pi" type="file" accept="image/*"></label></div><div class="modal-actions"><button class="ghost" onclick="this.closest(\'.modal\').remove()">Cancel</button><button class="primary" id="saveProd">Save Product</button></div>');
m.querySelector('#saveProd').onclick=async()=>{try{p.name=m.querySelector('#pn').value;p.category=m.querySelector('#pc').value;p.price=Math.max(0,Number(m.querySelector('#pp').value)||0);p.description=m.querySelector('#pd').value;p.active=m.querySelector('#pa').value==='true';const f=m.querySelector('#pi').files[0];if(f){const data=await cropImage(f,4/5),path='media/products/'+p._file.replace(/\.json$/,'')+'-'+Date.now()+'.jpg';await putDataUrl(path,data,null,'Update product image');p.image=path}const j=await save('data/products/'+p._file,JSON.stringify({name:p.name,category:p.category,price:p.price,description:p.description,image:p.image||'',active:p.active},null,2)+'\n',p._sha,'Update product from visual editor');p._sha=j.content?.sha||p._sha;m.remove();renderProducts();msg('Product saved.')}catch(e){msg('Product save failed: '+e.message)}}};
$('newProduct').onclick=async()=>{const file='product-'+Date.now()+'.json',p={name:'New Product',category:categories[0]?.name||'Watches',price:0,description:'',image:'',active:true,_file:file,_sha:null};try{const j=await save('data/products/'+file,JSON.stringify({name:p.name,category:p.category,price:0,description:'',image:'',active:true},null,2)+'\n',null,'Add product from visual editor');p._sha=j.content?.sha||null;products.unshift(p);renderProducts();editProduct(0)}catch(e){msg('Could not add product: '+e.message)}};
window.deleteProduct=async i=>{if(!confirm('Remove this product?'))return;try{const p=products[i];if(p._sha)await api('data/products/'+p._file,{method:'DELETE',body:JSON.stringify({message:'Remove product from visual editor',sha:p._sha})});products.splice(i,1);renderProducts();msg('Product removed.')}catch(e){msg('Remove failed: '+e.message)}};

const themeFields=[
['hero_desktop_height','Hero height — desktop','range',350,1200,10,'px'],['hero_mobile_height','Hero height — mobile','range',350,1000,10,'px'],
['hero_accessories_desktop_width','Hero image width — desktop','range',15,80,1,'%'],['hero_accessories_desktop_right','Hero image right — desktop','range',0,25,1,'vw'],['hero_accessories_desktop_y','Hero image vertical position — desktop','range',20,80,1,'%'],
['hero_accessories_mobile_width','Hero image width — mobile','range',50,160,1,'%'],['hero_accessories_mobile_right','Hero image right — mobile','range',-30,30,1,'%'],['hero_accessories_mobile_bottom','Hero image bottom — mobile','range',0,40,1,'%'],
['hero_copy_desktop_left','Hero text left — desktop','range',2,25,1,'vw'],['hero_copy_desktop_top','Hero text vertical position — desktop','range',20,80,1,'%'],['hero_copy_mobile_top','Hero text vertical position — mobile','range',5,70,1,'%'],
['hero_title_desktop_size','Hero title size — desktop','range',35,120,1,'px'],['hero_title_mobile_size','Hero title size — mobile','range',28,75,1,'px'],
['category_desktop_height','Category image height — desktop','range',120,500,5,'px'],['category_mobile_height','Category image height — mobile','range',90,350,5,'px'],['category_columns_desktop','Category columns — desktop','range',2,6,1,''],['category_columns_mobile','Category columns — mobile','range',1,3,1,''],
['product_columns_desktop','Product columns — desktop','range',2,6,1,''],['product_columns_mobile','Product columns — mobile','range',1,3,1,''],['product_image_ratio','Product image height ratio','range',80,150,1,'%'],
['section_spacing','Section spacing','range',20,160,4,'px'],['collection_padding','Collection top/bottom padding','range',30,160,5,'px'],['card_radius','Card roundness','range',0,40,1,'px'],['button_radius','Button roundness','range',0,40,1,'px'],['border_width','Border thickness','range',0,4,1,'px'],
['header_height_desktop','Header main height','range',45,110,1,'px'],['nav_gap','Navigation gap','range',10,60,1,'px'],['page_max_width','Content max width','range',900,1800,20,'px'],
['page_background','Page background','color','','','',''],['text_color','Main text color','color','','','',''],['accent_color','Accent / button color','color','','','',''],['muted_color','Muted text color','color','','','',''],
['header_text_color','Header text color','color','','','',''],['header_background','Header background','color','','','',''],['hero_text_color','Hero text color','color','','','',''],['hero_overlay','Hero overlay darkness','range',0,95,1,'%'],['collection_background','Collection background','color','','','',''],['collection_text_color','Collection text color','color','','','',''],['card_background','Product/card background','color','','','',''],['about_background','About background','color','','','',''],['about_text_color','About text color','color','','','',''],['contact_background','Contact background','color','','','','']
];
function fillTheme(){const f=$('themeForm');f.innerHTML=themeFields.map(x=>{const[k,l,type,min,max,step,suf]=x;if(type==='color')return '<label>'+l+'<input type="color" name="'+k+'" value="'+esc(theme[k]||'#191919')+'"></label>';return '<label class="theme-row"><span>'+l+'<small><output id="out-'+k+'">'+esc(theme[k]??min)+(suf)+'</output></small></span><input type="range" name="'+k+'" min="'+min+'" max="'+max+'" step="'+step+'" value="'+(theme[k]??min)+'" oninput="document.getElementById(\'out-'+k+'\').value=this.value+\''+suf+'\'"></label>'}).join('')+'<div class="full"><h3>Layout toggles</h3><div class="checks"><label><input type="checkbox" name="hero_background_enabled" '+(theme.hero_background_enabled!==false?'checked':'')+'> Show hero background image</label><label><input type="checkbox" name="hero_accessories_enabled" '+(theme.hero_accessories_enabled!==false?'checked':'')+'> Show hero product image</label><label><input type="checkbox" name="show_header" '+(theme.show_header!==false?'checked':'')+'> Show header</label></div></div>'}
$('saveTheme').onclick=async()=>{try{document.querySelectorAll('#themeForm [name]').forEach(e=>theme[e.name]=e.type==='range'?Number(e.value):e.type==='checkbox'?e.checked:e.value);await saveThemeObject();renderMedia();msg('Theme & layout saved. Refresh the storefront to see every change.')}catch(e){msg('Theme save failed: '+e.message)}};

$('loadFile').onclick=async()=>{try{const p=$('fileSelect').value,j=await read(p);$('fileEditor').value=j.text;$('fileEditor').dataset.sha=j.sha;msg('Loaded '+p)}catch(e){msg(e.message)}};
$('saveFile').onclick=async()=>{try{const p=$('fileSelect').value,sha=$('fileEditor').dataset.sha;if(!sha)return msg('Load the file first.');const j=await save(p,$('fileEditor').value,sha,'Update '+p+' from advanced editor');$('fileEditor').dataset.sha=j.content?.sha||sha;msg(p+' saved.')}catch(e){msg('File save failed: '+e.message)}};

function cropImage(file,aspect){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{let zoom=1,ox=0,oy=0,drag=false,lx=0,ly=0;const w=620,h=Math.round(w/aspect),m=openModal('<h2>Crop image</h2><p>Drag, zoom and position the image exactly how you want.</p><div class="crop-stage"><canvas id="cropCanvas" width="'+w+'" height="'+h+'"></canvas></div><div class="crop-controls"><label>Zoom <input id="cropZoom" type="range" min="1" max="3" step=".01" value="1"></label></div><div class="modal-actions"><button class="ghost" id="cropCancel">Cancel</button><button class="primary" id="cropSave">Use this crop</button></div>');const c=m.querySelector('#cropCanvas'),ctx=c.getContext('2d'),range=m.querySelector('#cropZoom');function fit(){const base=Math.max(w/img.width,h/img.height);zoom=base*Number(range.value);ox=(w-img.width*zoom)/2;oy=(h-img.height*zoom)/2}function draw(){ctx.clearRect(0,0,w,h);ctx.fillStyle='#111';ctx.fillRect(0,0,w,h);ctx.drawImage(img,ox,oy,img.width*zoom,img.height*zoom)}fit();draw();range.oninput=()=>{const cx=w/2,cy=h/2,old=zoom;zoom=Math.max(w/img.width,h/img.height)*Number(range.value);ox=cx-(cx-ox)*(zoom/old);oy=cy-(cy-oy)*(zoom/old);draw()};c.onpointerdown=e=>{drag=true;lx=e.clientX;ly=e.clientY;c.setPointerCapture(e.pointerId)};c.onpointermove=e=>{if(!drag)return;ox+=e.clientX-lx;oy+=e.clientY-ly;lx=e.clientX;ly=e.clientY;draw()};c.onpointerup=()=>drag=false;c.onpointercancel=()=>drag=false;m.querySelector('#cropCancel').onclick=()=>{m.remove();reject(new Error('Crop cancelled'))};m.querySelector('#cropSave').onclick=()=>{const type=file.type==='image/png'?'image/png':'image/jpeg',data=c.toDataURL(type,type==='image/jpeg'?.92:undefined);m.remove();resolve(data)}};img.onerror=reject;img.src=reader.result};reader.onerror=reject;reader.readAsDataURL(file)})}
