const REPO='akcollection/akcollection.github.io';let token='',site={},siteSha='',categories=[],catSha='',products=[],theme={},themeSha='';
const $=id=>document.getElementById(id);const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
function msg(t){const e=$('status');e.textContent=t;e.classList.add('show');clearTimeout(window._st);window._st=setTimeout(()=>e.classList.remove('show'),3500)}
function decode(b){return decodeURIComponent(escape(atob((b||'').replace(/\n/g,''))))}function encode(s){return btoa(unescape(encodeURIComponent(s)))}
async function api(path,opt={}){const r=await fetch('https://api.github.com/repos/'+REPO+'/contents/'+path,{...opt,headers:{Accept:'application/vnd.github+json',Authorization:'Bearer '+token,'Content-Type':'application/json'}});const j=await r.json();if(!r.ok)throw Error(j.message||'GitHub error');return j}
async function read(path){const j=await api(path);return {sha:j.sha,text:decode(j.content)}}
async function save(path,text,sha,message){const body={message,content:encode(text)};if(sha)body.sha=sha;return api(path,{method:'PUT',body:JSON.stringify(body)})}
function imagePath(p){return p?(p.startsWith('http')?p:'./'+p):''}
async function connect(){token=$('token').value.trim();if(!token)return msg('Paste your GitHub token.');try{msg('Loading your store...');let s=await read('data/site.json'),c=await read('data/categories.json'),t=await read('data/theme.json');site=JSON.parse(s.text);siteSha=s.sha;categories=JSON.parse(c.text);catSha=c.sha;theme=JSON.parse(t.text);themeSha=t.sha;let ls=await api('data/products');products=[];for(const f of ls.filter(x=>/\.json$/i.test(x.name))){let p=await read('data/products/'+f.name);products.push({...JSON.parse(p.text),_file:f.name,_sha:p.sha});}fillSite();renderCats();renderProducts();renderMedia();fillTheme();$('login').hidden=true;$('app').hidden=false;msg('Connected — full editor ready.')}catch(e){token='';msg('Connection failed: '+e.message)}}
$('connect').onclick=connect;$('logout').onclick=()=>{token='';location.reload()};
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$(b.dataset.tab).classList.add('active')});document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>document.querySelector('.tabs button[data-tab="'+b.dataset.go+'"]').click());
function fillSite(){const labels={announcement:'Top announcement',shipping:'Shipping / service bar',hero_label:'Hero small label',hero_title:'Hero main title',hero_emphasis:'Hero highlighted word',hero_text:'Hero description',hero_button:'Hero button text',about_label:'About small label',about_title:'About title',about_emphasis:'About highlighted words',about_text:'About paragraph',contact_label:'Contact small label',contact_title:'Contact title',contact_text:'Contact paragraph'};const keys=Object.keys(labels);$('siteForm').innerHTML=keys.map(k=>`<label>${labels[k]}<input name="${k}" value="${esc(site[k]||'')}"></label>`).join('')}
$('saveSite').onclick=async()=>{try{document.querySelectorAll('#siteForm [name]').forEach(e=>site[e.name]=e.value);let j=await save('data/site.json',JSON.stringify(site,null,2)+'\n',siteSha,'Update website content from visual editor');siteSha=j.content?.sha||siteSha;msg('Website text saved.')}catch(e){msg('Save failed: '+e.message)}};
function renderMedia(){const items=[{key:'hero_background',title:'Hero / Banner background',desc:'The large background behind the hero. Recommended 16:9.'},{key:'hero_accessories',title:'Hero product/accessories image',desc:'The cutout image shown in the hero.'},{key:'logo',title:'AK Collection logo',desc:'Header, mobile menu and footer logo.'}];$('mediaList').innerHTML=items.map(x=>{let p=theme[x.key]||'';return `<div class="media-card"><div class="media-preview">${p?`<img src="${imagePath(p)}" onerror="this.style.opacity=.25">`:'<span>No image set</span>'}</div><div class="inside"><h3>${x.title}</h3><p>${x.desc}</p><p><b>Current:</b> ${esc(p||'None')}</p><div class="buttons"><label class="ghost" style="cursor:pointer">Upload & crop<input type="file" accept="image/*" data-media="${x.key}" hidden></label><button class="ghost" onclick="clearMedia('${x.key}')">Clear</button></div></div></div>`}).join('');document.querySelectorAll('[data-media]').forEach(i=>i.onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const aspect=e.target.dataset.media==='hero_background'?16/9:e.target.dataset.media==='logo'?1:4/3;const data=await cropImage(f,aspect);const ext=e.target.dataset.media==='logo'?'png':'jpg';const path='media/site/'+e.target.dataset.media+'-'+Date.now()+'.'+ext;await putDataUrl(path,data,null,'Upload '+e.target.dataset.media+' from visual editor');theme[e.target.dataset.media]=path;await saveThemeObject();renderMedia();msg('Image uploaded and cropped.')}catch(err){msg('Image upload failed: '+err.message)}})}
window.clearMedia=async key=>{theme[key]='';try{await saveThemeObject();renderMedia();msg('Image removed.')}catch(e){msg(e.message)}};
async function saveThemeObject(){let j=await save('data/theme.json',JSON.stringify(theme,null,2)+'\n',themeSha,'Update visual theme from editor');themeSha=j.content?.sha||themeSha}
async function putDataUrl(path,dataUrl,sha,message){const content=dataUrl.split(',')[1];const body={message,content};if(sha)body.sha=sha;return api(path,{method:'PUT',body:JSON.stringify(body)})}
function renderCats(){const box=$('categoryList');box.innerHTML=categories.map((c,i)=>`<div class="category"><img src="${imagePath(c.image)}" onerror="this.style.visibility='hidden'"><div class="fields"><label>Name<input data-cat-name="${i}" value="${esc(c.label||c.name||'')}"></label><label>Link<input data-cat-link="${i}" value="${esc(c.link||'#collection')}"></label><small>${esc(c.image||'No image yet')}</small></div><div class="category-actions"><label class="ghost" style="cursor:pointer">Photo<input type="file" accept="image/*" data-cat-file="${i}" hidden></label><button class="danger" onclick="removeCat(${i})">Remove</button></div></div>`).join('');document.querySelectorAll('[data-cat-file]').forEach(el=>el.onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const i=+el.dataset.catFile,data=await cropImage(f,4/3),ext='jpg',path='media/categories/'+categories[i].id+'.'+ext;let oldSha=null;if(categories[i].image){try{oldSha=(await api(categories[i].image)).sha}catch(_){}}await putDataUrl(path,data,oldSha,'Update category image');categories[i].image=path;renderCats();msg('Category photo prepared — click Save Categories.')}catch(err){msg(err.message)}})}
$('addCategory').onclick=()=>{categories.push({id:'category-'+Date.now(),name:'NEW CATEGORY',label:'NEW CATEGORY',image:'',link:'#collection'});renderCats()};window.removeCat=i=>{if(confirm('Remove this category?')){categories.splice(i,1);renderCats()}};
$('saveCategories').onclick=async()=>{try{document.querySelectorAll('[data-cat-name]').forEach(el=>categories[+el.dataset.catName].name=categories[+el.dataset.catName].label=el.value);document.querySelectorAll('[data-cat-link]').forEach(el=>categories[+el.dataset.catLink].link=el.value||'#collection');let j=await save('data/categories.json',JSON.stringify(categories,null,2)+'\n',catSha,'Update categories from visual editor');catSha=j.content?.sha||catSha;msg('Categories saved.')}catch(e){msg('Category save failed: '+e.message)}};
function renderProducts(){const box=$('productsList');box.innerHTML=products.map((p,i)=>`<div class="product"><img src="${imagePath(p.image)}" onerror="this.style.visibility='hidden'"><div><h3>${esc(p.name||'Untitled')}</h3><p>PKR ${Number(p.price||0).toLocaleString()} · ${esc(p.category||'Watches')}</p><p>${esc(p.description||'')}</p><p>${p.active===false?'HIDDEN':'VISIBLE'}</p></div><div class="actions"><button class="primary" onclick="editProduct(${i})">Edit</button><button class="danger" onclick="deleteProduct(${i})">Remove</button></div></div>`).join('')||'<p>No products yet.</p>'}
function openModal(html){document.querySelector('.modal')?.remove();const d=document.createElement('div');d.className='modal';d.innerHTML='<div class="modalbox">'+html+'</div>';document.body.appendChild(d);return d}
window.editProduct=i=>{const p=products[i];const options=categories.map(c=>`<option ${p.category===c.name||p.category===c.label?'selected':''}>${esc(c.name||c.label)}</option>`).join('');const m=openModal(`<h2>Edit Product</h2><div class="formgrid"><label>Name<input id="pn" value="${esc(p.name)}"></label><label>Category<select id="pc">${options||'<option>Watches</option>'}</select></label><label>Price<input id="pp" type="number" value="${p.price||0}"></label><label>Description<textarea id="pd">${esc(p.description||'')}</textarea></label><label>Visibility<select id="pa"><option value="true" ${p.active!==false?'selected':''}>Visible</option><option value="false" ${p.active===false?'selected':''}>Hidden</option></select></label><label>Product photo<input id="pi" type="file" accept="image/*"></label></div><div class="modal-actions"><button class="ghost" onclick="this.closest('.modal').remove()">Cancel</button><button class="primary" id="saveProd">Save Product</button></div>`);m.querySelector('#saveProd').onclick=async()=>{try{p.name=m.querySelector('#pn').value;p.category=m.querySelector('#pc').value;p.price=Number(m.querySelector('#pp').value)||0;p.description=m.querySelector('#pd').value;p.active=m.querySelector('#pa').value==='true';const f=m.querySelector('#pi').files[0];if(f){const data=await cropImage(f,4/5),ext='jpg',path='media/products/'+p._file.replace(/\.json$/,'')+'.'+ext;let oldSha=null;if(p.image){try{oldSha=(await api(p.image)).sha}catch(_){}}await putDataUrl(path,data,oldSha,'Update product image');p.image=path;}let j=await save('data/products/'+p._file,JSON.stringify({name:p.name,category:p.category,price:p.price,description:p.description,image:p.image||'',active:p.active},null,2)+'\n',p._sha,'Update product from visual editor');p._sha=j.content?.sha||p._sha;m.remove();renderProducts();msg('Product saved.')}catch(e){msg('Product save failed: '+e.message)}}};
$('newProduct').onclick=async()=>{const file='product-'+Date.now()+'.json';const p={name:'New Product',category:categories[0]?.name||'Watches',price:0,description:'',image:'',active:true,_file:file,_sha:null};try{let j=await save('data/products/'+file,JSON.stringify({name:p.name,category:p.category,price:p.price,description:p.description,image:'',active:true},null,2)+'\n',null,'Add product from visual editor');p._sha=j.content?.sha||null;products.unshift(p);renderProducts();editProduct(0)}catch(e){msg('Could not add product: '+e.message)}};
window.deleteProduct=async i=>{if(!confirm('Remove this product?'))return;try{const p=products[i];if(p._sha)await api('data/products/'+p._file,{method:'DELETE',body:JSON.stringify({message:'Remove product from visual editor',sha:p._sha})});products.splice(i,1);renderProducts();msg('Product removed.')}catch(e){msg('Remove failed: '+e.message)}};
const themeFields=[['hero_desktop_height','Hero height — desktop','range',420,1000,10,'px'],['hero_mobile_height','Hero height — mobile','range',420,900,10,'px'],['hero_accessories_desktop_width','Hero image width — desktop','range',20,70,1,'%'],['hero_accessories_mobile_width','Hero image width — mobile','range',70,140,1,'%'],['hero_accessories_mobile_bottom','Hero image bottom — mobile','range',0,25,1,'%'],['category_desktop_height','Category image height — desktop','range',140,420,5,'px'],['category_mobile_height','Category image height — mobile','range',100,300,5,'px'],['section_spacing','Category section bottom spacing','range',20,120,4,'px'],['button_radius','Button roundness','range',0,30,1,'px'],['card_radius','Card roundness','range',0,30,1,'px'],['page_background','Page background','color','','','',''],['text_color','Main text color','color','','','',''],['accent_color','Accent / button color','color','','','',''],['muted_color','Muted text color','color','','','','']];
function fillTheme(){const f=$('themeForm');f.innerHTML=themeFields.map(x=>{const[k,l,type,min,max,step,suf]=x;if(type==='color')return `<label>${l}<input type="color" name="${k}" value="${esc(theme[k]||'#191919')}"></label>`;return `<label class="theme-row"><span>${l}<small><output id="out-${k}">${esc(theme[k]??min)}${suf}</output></small></span><input type="range" name="${k}" min="${min}" max="${max}" step="${step}" value="${theme[k]??min}" oninput="document.getElementById('out-${k}').value=this.value+'${suf}'"></label>`}).join('')}
$('saveTheme').onclick=async()=>{try{document.querySelectorAll('#themeForm [name]').forEach(e=>theme[e.name]=e.type==='range'?Number(e.value):e.value);await saveThemeObject();renderMedia();msg('Theme & layout saved. Refresh your website to see it.')}catch(e){msg('Theme save failed: '+e.message)}};
$('loadFile').onclick=async()=>{try{const p=$('fileSelect').value,j=await read(p);$('fileEditor').value=j.text;$('fileEditor').dataset.sha=j.sha;msg('Loaded '+p)}catch(e){msg(e.message)}};
$('saveFile').onclick=async()=>{try{const p=$('fileSelect').value,sha=$('fileEditor').dataset.sha;if(!sha)return msg('Load the file first.');let j=await save(p,$('fileEditor').value,sha,'Update '+p+' from advanced editor');$('fileEditor').dataset.sha=j.content?.sha||sha;msg(p+' saved.')}catch(e){msg('File save failed: '+e.message)}};
function cropImage(file,aspect){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{let zoom=1,ox=0,oy=0,drag=false,lx=0,ly=0;const w=620,h=Math.round(w/aspect),m=openModal(`<h2>Crop image</h2><p>Drag the image and use zoom to frame exactly what you want.</p><div class="crop-stage"><canvas id="cropCanvas" width="${w}" height="${h}"></canvas></div><div class="crop-controls"><label>Zoom <input id="cropZoom" type="range" min="1" max="3" step="0.01" value="1"></label></div><div class="modal-actions"><button class="ghost" id="cropCancel">Cancel</button><button class="primary" id="cropSave">Use this crop</button></div>`);const c=m.querySelector('#cropCanvas'),ctx=c.getContext('2d'),range=m.querySelector('#cropZoom');function fit(){const base=Math.max(w/img.width,h/img.height);zoom=base*Number(range.value);const dw=img.width*zoom,dh=img.height*zoom;ox=(w-dw)/2;oy=(h-dh)/2}function draw(){ctx.clearRect(0,0,w,h);ctx.fillStyle='#111';ctx.fillRect(0,0,w,h);ctx.drawImage(img,ox,oy,img.width*zoom,img.height*zoom)}fit();draw();range.oninput=()=>{const cx=w/2,cy=h/2,old=zoom;zoom=(Math.max(w/img.width,h/img.height))*Number(range.value);ox=cx-(cx-ox)*(zoom/old);oy=cy-(cy-oy)*(zoom/old);draw()};c.onpointerdown=e=>{drag=true;lx=e.clientX;ly=e.clientY;c.setPointerCapture(e.pointerId)};c.onpointermove=e=>{if(!drag)return;ox+=e.clientX-lx;oy+=e.clientY-ly;lx=e.clientX;ly=e.clientY;draw()};c.onpointerup=()=>drag=false;c.onpointercancel=()=>drag=false;m.querySelector('#cropCancel').onclick=()=>{m.remove();reject(new Error('Crop cancelled'))};m.querySelector('#cropSave').onclick=()=>{const type=file.type==='image/png'?'image/png':'image/jpeg';const quality=type==='image/jpeg'?0.92:undefined;const data=c.toDataURL(type,quality);m.remove();resolve(data)}};img.onerror=reject;img.src=reader.result};reader.onerror=reject;reader.readAsDataURL(file)})}
