/* AK COLLECTION — visual CMS runtime */
(function(){
  function getText(url){try{var x=new XMLHttpRequest();x.open('GET',url,false);x.send(null);return x.status>=200&&x.status<300?x.responseText:null}catch(e){return null}}
  function hashId(s){var h=0;for(var i=0;i<s.length;i++)h=((h<<5)-h)+s.charCodeAt(i)|0;return Math.abs(h)||1}
  function img(p){if(!p)return'';if(/^(https?:)?\\/\\//.test(p))return p;return p.indexOf('media/')===0?'/' + p:p}
  function safe(v){return String(v==null?'':v).replace(/[&<>"]/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]})}
  var site={},theme={},cats=[],products=[];
  var raw=getText('data/site.json');if(raw)try{site=JSON.parse(raw)}catch(e){}
  raw=getText('data/theme.json');if(raw)try{theme=JSON.parse(raw)}catch(e){}
  raw=getText('data/categories.json');if(raw)try{cats=JSON.parse(raw)}catch(e){}
  var listing=getText('https://api.github.com/repos/akcollection/akcollection.github.io/contents/data/products?ref=main');
  if(listing)try{JSON.parse(listing).filter(function(f){return/\\.json$/i.test(f.name)}).forEach(function(f){var q=getText('data/products/'+f.name);if(!q)return;try{var p=JSON.parse(q);if(p.active===false)return;products.push({id:hashId(f.name),name:p.name||f.name.replace(/\\.json$/i,''),type:p.category||'Watches',price:Number(p.price)||0,image:img(p.image),description:p.description||''})}catch(e){}})}catch(e){}
  window.__AK_PRODUCTS__=products;window.__AK_SITE__=site;window.__AK_CATEGORIES__=cats;window.__AK_THEME__=theme;

  function set(sel,v){var e=document.querySelector(sel);if(e&&v!=null)e.textContent=v}
  function show(sel,on){var e=document.querySelector(sel);if(e)e.style.display=on?'':'none'}
  function applyContent(){
    set('.announcement-bar span',site.announcement||'100% QUALITY CHECKED GUARANTEE');
    var ship=document.querySelector('.shipping-bar');if(ship)ship.innerHTML=(site.shipping||'FREE DELIVERY ON ALL ORDERS • PREMIUM WATCH COLLECTION • 24/7 CUSTOMER SUPPORT').split('•').map(function(x){return '<span>'+safe(x.trim())+'</span>'}).join('<span>•</span>');
    set('.hero-copy > span',site.hero_label||'AK COLLECTION');
    var h=document.querySelector('.hero-copy h1');if(h){h.textContent=site.hero_title||'TIMELESS';var em=document.createElement('em');em.textContent=site.hero_emphasis||'WATCHES';h.appendChild(em)}
    set('.hero-copy p',site.hero_text||'Premium designs made to complete your presence.');set('.hero-shop-btn',site.hero_button||'SHOP COLLECTION');
    [['.trust-bar>div:nth-child(1) strong',site.trust1_title],['.trust-bar>div:nth-child(1) span',site.trust1_text],['.trust-bar>div:nth-child(2) strong',site.trust2_title],['.trust-bar>div:nth-child(2) span',site.trust2_text],['.trust-bar>div:nth-child(3) strong',site.trust3_title],['.trust-bar>div:nth-child(3) span',site.trust3_text],['.trust-bar>div:nth-child(4) strong',site.trust4_title],['.trust-bar>div:nth-child(4) span',site.trust4_text]].forEach(function(a){if(a[1])set(a[0],a[1])});
    set('.category-heading span',site.category_label||'EXPLORE THE COLLECTION');var ch=document.querySelector('.category-heading h2');if(ch){ch.textContent=site.category_title||'SHOP BY ';var ce=document.createElement('em');ce.textContent=site.category_emphasis||'CATEGORY';ch.appendChild(ce)}
    set('.collection-header>div:first-child>span',site.collection_label||'AK COLLECTION');set('.collection-header h2',site.collection_title||'FEATURED WATCHES');set('.about>span',site.about_label||'ABOUT AK COLLECTION');var ah=document.querySelector('.about h2');if(ah){ah.textContent=site.about_title||'YOUR TIME. ';var ae=document.createElement('em');ae.textContent=site.about_emphasis||'YOUR STYLE.';ah.appendChild(ae)}set('.about p',site.about_text||'Discover premium watches selected for people who appreciate timeless design, elegant details and confident everyday style.');set('.contact span',site.contact_label||'HAVE A QUESTION?');set('.contact h2',site.contact_title||'TALK TO US');set('.contact p',site.contact_text||'Order your favourite watch directly through WhatsApp.');set('.contact-btn',site.contact_button||'WHATSAPP US');
    var fl=document.querySelector('.footer-logo strong');if(fl&&site.footer_brand)fl.textContent=site.footer_brand;var fs=document.querySelector('.footer-logo span');if(fs&&site.footer_subtitle)fs.textContent=site.footer_subtitle;var fp=document.querySelector('footer p');if(fp&&site.footer_copyright)fp.textContent=site.footer_copyright;
    if(site.browser_title)document.title=site.browser_title;var md=document.querySelector('meta[name="description"]');if(md&&site.browser_description)md.content=site.browser_description;
    show('.trust-bar',site.show_trust!==false);show('.category-showcase',site.show_categories!==false);show('.collection',site.show_collection!==false);show('.about',site.show_about!==false);show('.contact',site.show_contact!==false);
  }
  function renderCategories(){var g=document.getElementById('categoryGrid');if(!g)return;g.innerHTML=cats.map(function(c){return '<a class="category-card" href="'+safe(c.link||'#collection')+'"><div class="category-image">'+(c.image?'<img src="'+img(c.image)+'" alt="'+safe(c.name||c.label||'')+'">':'')+'</div><div class="category-card-name">'+safe(c.label||c.name||'CATEGORY')+'</div><span>'+safe(c.button||site.category_button||'SHOP NOW →')+'</span></a>'}).join('')}
  function applyTheme(){
    var t=theme,root=document.documentElement,n=function(v,d){var z=Number(v);return isFinite(z)?z:d},pct=function(v,d){return n(v,d)+'%'};
    var css=':root{--ak-page-bg:'+(t.page_background||'#f5f5f3')+';--ak-text:'+(t.text_color||'#191919')+';--ak-accent:'+(t.accent_color||'#191919')+';--ak-muted:'+(t.muted_color||'#777')+';--ak-button-radius:'+n(t.button_radius,8)+'px;--ak-card-radius:'+n(t.card_radius,0)+'px;}';
    css+='body{background:var(--ak-page-bg)!important;color:var(--ak-text)!important}.main-header{color:'+(t.header_text_color||'#fff')+'!important;background:'+(t.header_background||'linear-gradient(#000d,transparent)')+'!important}.header-main{height:'+n(t.header_height_desktop,70)+'px}.main-nav{gap:'+n(t.nav_gap,34)+'px}.hero-copy{left:'+n(t.hero_copy_desktop_left,7.5)+'vw;top:'+pct(t.hero_copy_desktop_top,53)+'}.hero-copy h1{font-size:'+n(t.hero_title_desktop_size,94)+'px;color:'+(t.hero_text_color||'#fff')+'}.hero-background{background-image:linear-gradient(90deg,rgba(0,0,0,'+n(t.hero_overlay,48)/100+'),rgba(0,0,0,.05)),var(--ak-hero-bg)!important}.luxury-hero{min-height:'+n(t.hero_desktop_height,720)+'px}.hero-accessories{width:min('+n(t.hero_accessories_desktop_width,44)+'vw,900px);right:'+n(t.hero_accessories_desktop_right,5)+'vw;top:'+pct(t.hero_accessories_desktop_y,50)+'}.trust-bar{display:grid}.category-showcase{padding-bottom:'+n(t.section_spacing,64)+'px}.category-grid{grid-template-columns:repeat('+n(t.category_columns_desktop,4)+',1fr)}.category-image{height:'+n(t.category_desktop_height,245)+'px}.collection{padding-top:'+n(t.collection_padding,90)+'px;padding-bottom:'+n(t.collection_padding,100)+'px;background:'+(t.collection_background||'#f5f5f3')+'!important;color:'+(t.collection_text_color||'#080808')+'!important}.products-grid{grid-template-columns:repeat('+n(t.product_columns_desktop,4)+',1fr)}.product-image{aspect-ratio:1/'+(n(t.product_image_ratio,120)/100)+'}.product-card{background:'+(t.card_background||'#fff')+'!important;border-width:'+n(t.border_width,1)+'px}.product-card,.category-card{border-radius:var(--ak-card-radius);overflow:hidden}.hero-shop-btn,.contact-btn,.checkout-btn,.modal-add{background:var(--ak-accent)!important;border-radius:var(--ak-button-radius)}.about{background:'+(t.about_background||'#080808')+'!important;color:'+(t.about_text_color||'#fff')+'!important}.contact{background:'+(t.contact_background||'#fff')+'!important}.main-header{display:'+(t.show_header===false?'none':'')+'}';
    css+='@media(max-width:699px){.header-main{height:auto}.luxury-hero{min-height:'+n(t.hero_mobile_height,620)+'px;height:'+n(t.hero_mobile_height,620)+'px}.hero-copy{left:20px;top:'+n(t.hero_copy_mobile_top,18)+'%;transform:none}.hero-copy h1{font-size:'+n(t.hero_title_mobile_size,47)+'px}.hero-accessories{width:'+n(t.hero_accessories_mobile_width,116)+'%;right:'+n(t.hero_accessories_mobile_right,-8)+'%;top:auto;bottom:'+n(t.hero_accessories_mobile_bottom,5)+'%}.category-grid{grid-template-columns:repeat('+n(t.category_columns_mobile,2)+',1fr)}.category-image{height:'+n(t.category_mobile_height,165)+'px}.collection{padding-top:'+Math.max(20,n(t.collection_padding,60)/1.5)+'px;padding-bottom:'+Math.max(20,n(t.collection_padding,70)/1.5)+'px}.products-grid{grid-template-columns:repeat('+n(t.product_columns_mobile,2)+',1fr)}.product-card img{aspect-ratio:1/'+(n(t.product_image_ratio,120)/100)}}';
    var old=document.getElementById('ak-visual-theme');if(old)old.remove();var st=document.createElement('style');st.id='ak-visual-theme';st.textContent=css;document.head.appendChild(st);
    if(t.hero_background_enabled!==false&&t.hero_background){root.style.setProperty('--ak-hero-bg','url("'+img(t.hero_background)+'")')}else root.style.setProperty('--ak-hero-bg','none');
    var acc=document.querySelector('.hero-accessories');if(acc){acc.style.display=t.hero_accessories_enabled===false?'none':'';if(t.hero_accessories)acc.src=img(t.hero_accessories)}
    document.querySelectorAll('.header-logo img,.mobile-menu-logo,.footer-logo img').forEach(function(e){if(t.logo)e.src=img(t.logo)});
    [['.hero-watches .watch-one img',t.hero_watch1],['.hero-watches .watch-two img',t.hero_watch2],['.hero-watches .watch-three img',t.hero_watch3],['.hero-watches .watch-four img',t.hero_watch4]].forEach(function(a){if(a[0]&&a[1]){var e=document.querySelector(a[0]);if(e)e.src=img(a[1])}});
  }
  function filters(){var box=document.querySelector('.filters');if(!box)return;var vals=[site.filter_all||'All'].concat(cats.map(function(c){return c.name||c.label}).filter(Boolean));vals=vals.filter(function(v,i,a){return a.indexOf(v)===i});box.innerHTML=vals.map(function(v,i){return '<button class="filter'+(i===0?' active':'')+'" data-filter="'+safe(v)+'">'+safe(v.toUpperCase())+'</button>'}).join('')}
  var rawScript=getText('script.js');if(rawScript){rawScript=rawScript.replace('const products = [','const products = window.__AK_PRODUCTS__ || [');var s=document.createElement('script');s.text=rawScript;document.body.appendChild(s)}
  filters();renderCategories();applyContent();applyTheme();
})();