const WHATSAPP_NUMBER = "923709039540"; // AK Collection WhatsApp: 03709039540
const products=[
{id:1,name:"Royal Blue",cat:"Men • Luxury",price:6800,type:["men","luxury"],badge:"FEATURED",image:"blue-leather.jpg",material:"Leather strap",style:"Luxury",description:"A rich blue statement piece with a refined rectangular profile, made for formal looks and special occasions."},
{id:2,name:"Azure Steel",cat:"Men • Classic",price:2999,type:["men","classic"],badge:"NEW",image:"blue-dial.jpg",material:"Steel bracelet",style:"Classic",description:"A clean blue-dial design with a polished steel look that works effortlessly for everyday wear."},
{id:3,name:"Silver Chrono",cat:"Men • Modern",price:4000,type:["men","luxury"],badge:"POPULAR",image:"silver-chronograph.jpg",material:"Steel finish",style:"Modern",description:"A bold silver chronograph-inspired design for a confident, contemporary presence."},
{id:4,name:"Prestige Set",cat:"Luxury • Set",price:7200,type:["classic","luxury","set"],badge:"LIMITED",image:"silver-set.jpg",material:"Premium set",style:"Gift Set",description:"A coordinated silver and white watch set, ideal for gifting or building a versatile collection."},
{id:5,name:"White Elegance",cat:"Classic • Luxury",price:2800,type:["classic","luxury"],badge:"NEW",image:"white-dial.jpg",material:"Classic finish",style:"Elegant",description:"A clean white-dial look with timeless styling for simple, polished outfits."}
];
let cart=JSON.parse(localStorage.getItem("akCart")||"[]"), activeFilter="all", searchTerm="";
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s), money=n=>`PKR ${n.toLocaleString("en-PK")}`;
function renderProducts(){const list=products.filter(p=>(activeFilter==="all"||p.type.includes(activeFilter))&&(`${p.name} ${p.cat} ${p.style}`.toLowerCase().includes(searchTerm.toLowerCase())));$('#resultsCount').textContent=`${list.length} WATCH${list.length===1?'':'ES'} AVAILABLE`;$('#clearSearch').style.visibility=searchTerm||activeFilter!=="all"?'visible':'hidden';$('#products').innerHTML=list.length?list.map(p=>`<article class="product"><div class="product-img"><span class="badge">${p.badge}</span><img class="real-watch" src="${p.image}" alt="${p.name} watch"></div><div class="product-info"><span class="category">${p.cat}</span><h3>${p.name}</h3><div class="price"><span>${money(p.price)}</span><div class="card-actions"><button class="details-btn" data-details="${p.id}">VIEW</button><button class="add" data-id="${p.id}">ADD</button></div></div></div></article>`).join(''):`<div class="empty" style="grid-column:1/-1">No watches found. Try another search.</div>`;$$('.add').forEach(b=>b.onclick=()=>addToCart(+b.dataset.id));$$('[data-details]').forEach(b=>b.onclick=()=>showDetails(+b.dataset.details));}
function addToCart(id){const f=cart.find(x=>x.id===id);f?f.qty++:cart.push({id,qty:1});saveCart();openCart()}
function saveCart(){localStorage.setItem('akCart',JSON.stringify(cart));renderCart()}
function renderCart(){const el=$('#cartItems'),count=cart.reduce((s,x)=>s+x.qty,0);$('#cartCount').textContent=count;if(!cart.length){el.innerHTML='<p class="empty">Your bag is waiting.</p>';$('#cartTotal').textContent='PKR 0';return}el.innerHTML=cart.map(x=>{const p=products.find(y=>y.id===x.id);return `<div class="cart-row"><div><h4>${p.name}</h4><small>${money(p.price)} each</small><div class="qty"><button data-minus="${p.id}">−</button><span>${x.qty}</span><button data-plus="${p.id}">+</button></div></div><div><strong>${money(p.price*x.qty)}</strong><br><button class="remove" data-remove="${p.id}">REMOVE</button></div></div>`}).join('');$('#cartTotal').textContent=money(cart.reduce((s,x)=>s+products.find(p=>p.id===x.id).price*x.qty,0));$$('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(x=>x.id!==+b.dataset.remove);saveCart()});$$('[data-plus]').forEach(b=>b.onclick=()=>changeQty(+b.dataset.plus,1));$$('[data-minus]').forEach(b=>b.onclick=()=>changeQty(+b.dataset.minus,-1))}
function changeQty(id,delta){const f=cart.find(x=>x.id===id);if(!f)return;f.qty+=delta;if(f.qty<=0)cart=cart.filter(x=>x.id!==id);saveCart()}
function openCart(){$('#cart').classList.add('open');$('#overlay').classList.add('show')};function closeCart(){$('#cart').classList.remove('open');$('#overlay').classList.remove('show')}
$('#cartOpen').onclick=openCart;$('#cartClose').onclick=closeCart;$('#overlay').onclick=closeCart;
$$('.filter').forEach(b=>b.onclick=()=>{$$('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeFilter=b.dataset.filter;renderProducts()});
$('#search').oninput=e=>{searchTerm=e.target.value;renderProducts()};$('#clearSearch').onclick=()=>{$('#search').value='';searchTerm='';activeFilter='all';$$('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter==='all'));renderProducts()};
function showDetails(id){const p=products.find(x=>x.id===id);$('#modalContent').innerHTML=`<div class="modal-product"><img src="${p.image}" alt="${p.name}"><div class="modal-info"><p class="eyebrow">${p.badge}</p><h3>${p.name}</h3><div class="modal-price">${money(p.price)}</div><p style="color:#999;font-size:12px">${p.description}</p><div class="specs"><div><span>Category</span><strong>${p.cat}</strong></div><div><span>Style</span><strong>${p.style}</strong></div><div><span>Finish</span><strong>${p.material}</strong></div><div><span>Delivery</span><strong>Pakistan-wide</strong></div></div><button class="gold-btn full" id="modalAdd">ADD TO BAG →</button></div></div>`;$('#productModal').classList.add('show');$('#modalAdd').onclick=()=>{addToCart(id);$('#productModal').classList.remove('show')}}
$('#modalClose').onclick=()=>$('#productModal').classList.remove('show');$('#productModal').onclick=e=>{if(e.target.id==='productModal')$('#productModal').classList.remove('show')};
function baseWhatsApp(text){return `https://wa.me/${WHATSAPP_NUMBER}?text=${encodeURIComponent(text)}`}
$('#heroWhatsapp').href=baseWhatsApp('Assalam-o-Alaikum AK Collection! I want to know more about your watches.');$('#whatsappContact').href=baseWhatsApp('Assalam-o-Alaikum AK Collection! I want to know more about your watches.');
$('#checkout').onclick=()=>{if(!cart.length){alert('Please add a watch to your bag first.');return}$('#checkoutModal').classList.add('show')};$('#checkoutClose').onclick=()=>$('#checkoutModal').classList.remove('show');
$('#orderForm').onsubmit=e=>{e.preventDefault();const lines=cart.map(x=>{const p=products.find(y=>y.id===x.id);return `${p.name} x${x.qty} — ${money(p.price*x.qty)}`}).join('\n');const total=cart.reduce((s,x)=>s+products.find(p=>p.id===x.id).price*x.qty,0);const msg=`Assalam-o-Alaikum AK Collection!\n\nI want to place an order:\n${lines}\n\nTotal: ${money(total)}\n\nCustomer Name: ${$('#customerName').value}\nPhone: ${$('#customerPhone').value}\nCity: ${$('#customerCity').value}\nAddress: ${$('#customerAddress').value}`;window.open(baseWhatsApp(msg),'_blank');};
$('#menuBtn').onclick=()=>$('#nav').classList.toggle('open');$$('#nav a').forEach(a=>a.onclick=()=>$('#nav').classList.remove('open'));
renderProducts();renderCart();
